###########################################################
# Copyright (C) 2015-2016 Shawn Mehan <shawn dot mehan at shawnmehan dot com>
# day 2 of AOC_2016
###########################################################
#
#  -*- coding: utf-8 -*-

# standard libs

# 3rd party libs

# application libs

test_directions = ['ULL', 'RRDDD', 'LURDL', 'UUUUD']
test_soln = '1985'

directions = ['ULUULLUULUUUUDURUUULLDLDDRDRDULULRULLRLULRUDRRLDDLRULLLDRDRRDDLLLLDURUURDUDUUURDRLRLLURUDRDULURRUDLRDRRLLRDULLDURURLLLULLRLUDDLRRURRLDULRDDULDLRLURDUDRLLRUDDRLRDLLDDUURLRUDDURRLRURLDDDURRDLLDUUDLLLDUDURLUDURLRDLURURRLRLDDRURRLRRDURLURURRRULRRDLDDDDLLRDLDDDRDDRLUUDDLDUURUULDLUULUURRDRLDDDULRRRRULULLRLLDDUDRLRRLLLLLDRULURLLDULULLUULDDRURUDULDRDRRURLDRDDLULRDDRDLRLUDLLLDUDULUUUUDRDRURDDULLRDRLRRURLRDLRRRRUDDLRDDUDLDLUUDLDDRRRDRLLRLUURUDRUUULUDDDLDUULULLRUDULULLLDRLDDLLUUDRDDDDRUDURDRRUUDDLRRRRURLURLD',
'LDLUDDLLDDRLLDLDRDDDDDUURUDDDUURLRLRLDULLLDLUDDDULLDUDLRUUDDLUULLDRLDDUDLUDDLURRRLDUURDDRULLURLLRLLUUDRLDDDLDLDRDUDLRDURULDLDRRDRLDLUURRRRLUDDULDULUUUDULDDRLLDDRRUULURRUURRLDUUUDDDDRUURUDRRRDDDDLRLURRRRUUDDDULRRURRDLULRURDDRDRLUDLURDDRDURRUURDUDUDRRDDURRRDURDLUUUURRUDULLDDRLLLURLDUDRRLDDLULUDUDDDDUDLUUULUURUDRURUUDUUURRLDUUDRDRURLLDLLLLLRLLUDURDRRLULRRDDDRLDRDDURLRDULULLDDURURLRRDRULDULUUUURLDURUDUDUDDLUDRRDURULRDULLLDRRDLDLUDURDULULLDDURDDUDRUUUDUDRLDUURDUUUDUURURUDRULRURLDLRDDURDLUU',
'DDLDRLLDRRDRRLLUUURDDULRDUDRDRUDULURLLDDLRRRUDRDLDLURRRULUDRDLULLULLDUUDRLRUDDLRRURRUULRLDLLLDLRLLLURLLLURLLRDDLULLDUURLURDLLDLDUDLDRUUUDDLLDRRRRRUDRURUURRRDRUURDRDDRLDUUULUDUDRUDLLLLDRDRURRRDUUURLDLRLRDDDRLUDULDRLLULRDLDURDLDURUUDDULLULRDDRLRUURLLLURDRUURUUDUUULRDUDDRDURRRDUUDRRRUDRDLRURDLLDDDURLLRRDDDDLDULULDRLDRULDDLRRRLUDLLLLUDURRRUURUUULRRLDUURDLURRLRLLRDLRDDRDDLRDLULRUUUDDDUDRRURDDURURDDUDLURUUURUUUUDURDDLDRDULDRLDRLLRLRRRLDRLLDDRDLDLUDDLUDLULDLLDRDLLRDULDUDDULRRRUUDULDULRRURLRDRUDLDUDLURRRDDULRDDRULDLUUDDLRDUURDRDR',
'URDURRRRUURULDLRUUDURDLLDUULULDURUDULLUDULRUDUUURLDRRULRRLLRDUURDDDLRDDRULUUURRRRDLLDLRLRULDLRRRRUDULDDURDLDUUULDURLLUDLURULLURRRDRLLDRRDULUDDURLDULLDURLUDUULRRLLURURLDLLLURDUDRLDDDRDULLUDDRLDDRRRLDULLLLDUURULUDDDURUULUUUDURUDURDURULLLDRULULDRRLDRLDLRLRUDUDURRLURLRUUDRRDULULDLLDRDRRRDUDUURLDULLLURRDLUDDLDDRDDUDLDDRRRUDRULLURDDULRLDUDDDRULURLLUDLLRLRRDRDRRURUUUURDLUURRDULLRDLDLRDDRDRLLLRRDDLDDDDLUDLRLULRRDDRDLDLUUUDLDURURLULLLDDDULURLRRURLDDRDDLD',
'UDUULLRLUDLLUULRURRUUDDLLLDUURRURURDDRDLRRURLLRURLDDDRRDDUDRLLDRRUDRDRDDRURLULDDLDLRRUDDULLRLDDLRURLUURUURURDLDUDRLUUURRRLUURUDUDUUDDLDULUULRLDLLURLDRUDRLLRULURDLDDLLULLDRRUUDDLRRRUDDLRDRRRULDRDDRRULLLUDRUULURDUDRDLRRLDLRLRLDDULRRLULUUDDULDUDDULRRURLRDRDURUDDDLLRLDRDRULDDLLRLLRDUDDDDDDRLRLLDURUULDUUUDRURRLLRLDDDDRDRDUURRURDRDLLLUDDRDRRRDLUDLUUDRULURDLLLLLRDUDLLRULUULRLULRURULRLRRULUURLUDLDLLUURDLLULLLDDLRUDDRULRDLULRUURLDRULRRLULRLRULRDLURLLRURULRDRDLRRLRRDRUUURURULLLDDUURLDUDLLRRLRLRULLDUUUULDDUUU']

dial = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]


pad = {'1': {'U': '1', 'R': '2', 'D': '4', 'L': '1'},
       '2': {'U': '2', 'R': '3', 'D': '5', 'L': '1'},
       '3': {'U': '3', 'R': '3', 'D': '6', 'L': '2'},
       '4': {'U': '1', 'R': '5', 'D': '7', 'L': '4'},
       '5': {'U': '2', 'R': '6', 'D': '8', 'L': '4'},
       '6': {'U': '3', 'R': '6', 'D': '9', 'L': '5'},
       '7': {'U': '4', 'R': '8', 'D': '7', 'L': '7'},
       '8': {'U': '5', 'R': '9', 'D': '8', 'L': '7'},
       '9': {'U': '6', 'R': '9', 'D': '9', 'L': '8'}}

soln = '5DB3'

new_dial = """   1
               2 3 4
             5 6 7 8 9
               A B C
                 D"""

pad = {'1': {'U': '1', 'R': '1', 'D': '3', 'L':'1'},
       '2': {'U': '2', 'R': '3', 'D': '6', 'L':'2'},
       '3': {'U': '1', 'R': '4', 'D': '7', 'L':'2'},
       '4': {'U': '4', 'R': '4', 'D': '8', 'L':'3'},
       '5': {'U': '5', 'R': '6', 'D': '5', 'L':'5'},
       '6': {'U': '2', 'R': '7', 'D': 'A', 'L':'5'},
       '7': {'U': '3', 'R': '8', 'D': 'B', 'L':'6'},
       '8': {'U': '4', 'R': '9', 'D': 'C', 'L':'7'},
       '9': {'U': '9', 'R': '9', 'D': '9', 'L':'8'},
       'A': {'U': '6', 'R': 'B', 'D': 'A', 'L':'A'},
       'B': {'U': '7', 'R': 'C', 'D': 'D', 'L':'A'},
       'C': {'U': '8', 'R': 'C', 'D': 'C', 'L':'B'},
       'D': {'U': 'B', 'R': 'D', 'D': 'D', 'L':'D'}}

state = '5'  # initial state on pad
out = []
for line in directions:
    for e in line:
        state = pad[state][e]
    out.append(state)
print(out)
